name: Deploy documentation on GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      - name: Install ComNetsEmu
        run: |
          # Full upgrade is too slow...
          sudo apt-get update -qq
          # Remove the pre-installed versions on the CI VM. They are too old and lead to install errors
          sudo apt-get remove -q -y docker docker-engine docker.io containerd runc
          # The CI VM can not resolve the runc and containerd dependency of docker.io automatically... I don't know the detailed reason yet...
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y runc containerd
          PYTHON=python3 ./util/install.sh -a
          PYTHON=python3 ./util/install.sh -d

      - name: Build HTML docs
        run: |
          make doc

      - name: Deploy HTML docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/build/html
